### PR TITLE
Started updating the SAL/XML test environment with SAL v6.0 updates; …

### PR DESCRIPTION
**Pull request by rbovill**
…additional software for building the documentation.  Permissions cleanup in the image home directory.

Added rdfind to the yum install list in robotsal/Dockerfile.

Updated robot/Test_Vars.txt with the new skiponfailure flag that replaces the deprecated noncritical flag in Robot-Framework v4.  Also updated Robot-Frameowork in the robot image to v4.

Upgrade to OpenSplice v6.11. Using ssh keys to authenticate to GitHub.

### CODE REVIEW

**Comment by wvreeven** [comment]
Was it decided that we start using OpenSplce 6.11? I thought we were supposed to use 6.10 still.

**Comment by rbovill** [comment]
We are not using 6.11.  This is just part of the process of cleaning up my branches in preparation for removing this repo.

**Comment by rbovill** [comment]
This PR will delete this branch.  The next PR will get all my work synced up.  Then I will migrate my Dockerfiles to my robotframework repos.

**Review by couger01 — APPROVED** [review]
LGTM.

**Pull request merged**
